Just a simple jupyter to study stuff (embedding and attention)

In [4]:
import torch
from torch import nn
import numpy as np

In [5]:
class Network():
    def __init__(self):
        layer = torch.nn.Embedding(3,2)
        final_layer = nn.Linear(2,1)
        activation_fun = nn.Sigmoid(final)
    def __call__(inp):
        partial = layer(sol)
        final = nn.Sigmoid(final_layer(partial))
        return final

In [6]:
input_tensor = torch.tensor([[1],[2],[3],[0]], dtype=torch.long)
sol =  torch.tensor([1,1,0])

In [7]:
#The two layers
layer = torch.nn.Embedding(4,2)
final_layer = nn.Linear(2,1)

In [11]:
layer(input_tensor)

tensor([[[ 1.4803,  0.9578]],

        [[ 1.9680,  1.0638]],

        [[-0.4979,  0.5636]],

        [[ 1.3821, -0.2303]]], grad_fn=<EmbeddingBackward>)

In [16]:
src = torch.tensor([[1,0,4,3],[1,2,3,0]],dtype=torch.long)
pos = torch.arange(0, src.shape[1]).unsqueeze(0).repeat(2, 1)
print(src)
print(pos)

tensor([[1, 0, 4, 3],
        [1, 2, 3, 0]])
tensor([[0, 1],
        [0, 1]])


In [3]:
def calculate_attention(self, embedded, conved, encoder_conved, encoder_combined):
    
    #embedded = [batch size, trg len, emb dim]
    #conved = [batch size, hid dim, trg len]
    #encoder_conved = encoder_combined = [batch size, src len, emb dim]
    
    #permute and convert back to emb dim
    conved_emb = self.attn_hid2emb(conved.permute(0, 2, 1))
    
    #conved_emb = [batch size, trg len, emb dim]
    
    combined = (conved_emb + embedded) * self.scale
    
    #combined = [batch size, trg len, emb dim]
            
    energy = torch.matmul(combined, encoder_conved.permute(0, 2, 1))
    
    #energy = [batch size, trg len, src len]
    
    attention = F.softmax(energy, dim=2)
    
    #attention = [batch size, trg len, src len]
        
    attended_encoding = torch.matmul(attention, encoder_combined)
    
    #attended_encoding = [batch size, trg len, emd dim]
    
    #convert from emb dim -> hid dim
    attended_encoding = self.attn_emb2hid(attended_encoding)
    
    #attended_encoding = [batch size, trg len, hid dim]
    
    #apply residual connection
    attended_combined = (conved + attended_encoding.permute(0, 2, 1)) * self.scale
    
    #attended_combined = [batch size, hid dim, trg len]
    
    return attention, attended_combined