Just a small tutorial on how to use the library.
Install it by typing:
pip3 install -e DatasetCreatorLib/ 

The e flag will allow to make modification in the code and avoid the need of reinstalling it

In [1]:
%load_ext autoreload
%autoreload 

from eq_learner.DatasetCreator import DatasetCreator
from sympy import sin, Symbol, log, exp 
import numpy as np

The basis function order **is important**. Note that the basis functions should be passed **without** the independent variable (i.e. sin and not sin(x))

In [2]:
x = Symbol('x')
basis_functions = [x,sin,log,exp]

Create a func generator object. As argument you need to pass the basis_function and some keywords arguments regarding how many terms from each class you want to have.


In [3]:
fun_generator = DatasetCreator(basis_functions, constants_enabled=False)

Call the fun_generator with no arguments for return the equation string and a dictionary containing a list of each added.

**Idea for Tokenization**: Instead of using the string (on which we do not have so much control as simpy does not allow added ordering), shall we use tokenize using the dictionary? the plus sign could be bypassed and considered as a space in NLP

In [4]:
string, dictionary, dictionary_clean =  fun_generator.generate_fun()
print("string: \n  {} \n".format(string))
print("dictionary \n {} \n".format(dictionary))
print("dictionary clean \n {} \n".format(dictionary_clean))


string: 
  exp(sin(x)**2 + sin(x)) + exp(log(x)**3 + log(x)**2 + 1) 

dictionary 
 {'Single': [], 'binomial': [], 'N_terms': [], 'compositions': [exp(log(x)**3 + log(x)**2 + 1), exp(sin(x)**2 + sin(x))], 'division': []} 

dictionary clean 
 {'Single': [], 'binomial': [], 'N_terms': [], 'compositions': [exp(log(x)**3 + log(x)**2 + 1), exp(sin(x)**2 + sin(x))], 'division': []} 



To make prediction use evaluate function

In [5]:
support = np.arange(1,20)
y = fun_generator.evaluate_function(support,string)
support,y

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19]),
 array([7.42760597e+00, 1.18070108e+01, 3.53984100e+01, 2.67501181e+02,
        2.34399540e+03, 2.12201971e+04, 1.90022877e+05, 1.64911126e+06,
        1.37362331e+07, 1.09339652e+08, 8.30521139e+08, 6.02067895e+09,
        4.16962813e+10, 2.76275535e+11, 1.75434948e+12, 1.06953047e+13,
        6.27122929e+13, 3.54288963e+14, 1.93171589e+15]))

You can also generate batch of equation in a single step with generate_batch

In [9]:
support = np.arange(1,20)
number_to_generate = 5
res = fun_generator.generate_batch(support, number_to_generate)
tokenization.pipeline(res)

print("Number of equations", len(res))
print("Example", res[0])

NameError: name 'tokenization' is not defined

In [8]:
support = np.arange(1,5)
number_to_generate = 5
res = fun_generator.generate_batch(support, number_to_generate)
res

([array([[ 1.        ,  2.        ,  3.        ,  4.        ],
         [ 0.93591468,  1.00654058,  0.14931173, -0.20340524]]),
  array([[1.00000000e+00, 2.00000000e+00, 3.00000000e+00, 4.00000000e+00],
         [4.17163711e+02, 1.62828498e+05, 6.56604943e+07, 2.64891262e+10]]),
  array([[ 1.        ,  2.        ,  3.        ,  4.        ],
         [ 1.81859485,  0.37728878,  4.09442327, 15.74433474]]),
  array([[ 1.        ,  2.        ,  3.        ,  4.        ],
         [ 1.34283895,  1.59293173,  0.14151661, -0.42875991]]),
  array([[1.00000000e+00, 2.00000000e+00, 3.00000000e+00, 4.00000000e+00],
         [5.95082432e+01, 3.26902316e+06, 2.35385267e+17, 8.22301271e+36]])],
 [{'Single': [],
   'binomial': [],
   'N_terms': [],
   'compositions': [log(sin(x)**2 + sin(x) + 1)],
   'division': []},
  {'Single': [exp(6*x) + exp(2*x) + exp(x)],
   'binomial': [],
   'N_terms': [],
   'compositions': [sin(x**3 + x), x*exp(log(x)**3 + log(x)**2 + 1)],
   'division': []},
  {'Single': [l

ToDo for the future:

1. Add X and Y noise
2. Constrains solution to 0 if there are Nan or +/- inf
3. Add constants